"""Database management and data layer package."""

from .database import (
    DEFAULT_DB_PATH,
    DatabaseManager,
    create_tables,
    get_connection,
    get_db_context,
    init_database,
    resolve_db_path,
)
from .queries import (
    get_account_history,
    get_available_symbols,
    get_backtest_results,
    get_candle_count,
    get_candles,
    get_features,
    get_indicators,
    get_latest_account_snapshot,
    get_model_versions,
    get_predictions,
    get_trades,
    insert_account_snapshot,
    insert_backtest_result,
    insert_candles,
    insert_features,
    insert_indicators,
    insert_model_version,
    insert_prediction,
    insert_trade,
    update_trade,
)
from .schema import ALL_TABLES, INDICES, SCHEMA_VERSION

__all__ = [
    "SCHEMA_VERSION",
    "ALL_TABLES",
    "INDICES",
    "DEFAULT_DB_PATH",
    "resolve_db_path",
    "get_connection",
    "get_db_context",
    "create_tables",
    "init_database",
    "DatabaseManager",
    "insert_candles",
    "get_candles",
    "get_candle_count",
    "get_available_symbols",
    "insert_indicators",
    "get_indicators",
    "insert_features",
    "get_features",
    "insert_prediction",
    "get_predictions",
    "insert_trade",
    "update_trade",
    "get_trades",
    "insert_account_snapshot",
    "get_latest_account_snapshot",
    "get_account_history",
    "insert_model_version",
    "get_model_versions",
    "insert_backtest_result",
    "get_backtest_results",
]
